services:
  mysql:
    image: mariadb:11.4
    container_name: mydb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: restaurant
      MYSQL_PASSWORD: restaurant
      MYSQL_DATABASE: restaurant
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my-network

  be:
    image: ${REGISTRY_URL}/${REGISTRY_USER}/${REGISTRY_PROJECT}-be:${IMAGE_TAG}
    build: ./backend
    container_name: mybe
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/restaurant
      SPRING_DATASOURCE_USERNAME: restaurant
      SPRING_DATASOURCE_PASSWORD: restaurant
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - my-network

  fe:
    image: ${REGISTRY_URL}/${REGISTRY_USER}/${REGISTRY_PROJECT}-fe:${IMAGE_TAG}
    build: ./frontend
    container_name: myfe
    ports:
      - "80:80"
    depends_on:
      - be
    networks:
      - my-network

volumes:
  db_data:

networks:
  my-network:
    driver: bridge
